### ISSUE TITLE
SLES 15 sysdep problems

### ISSUE THREAD

**Issue by colearendt** [rstudio/r-docker#30]
@glin @slopp 

Feedback on SLES 15 (using an AWS AMI, I believe? @ChaitaC may be able to provide more direction about the image she used):
When executing the sysdeps command:
```
No provider of 'pango-tools' found.
'atlascpp-devel' not found in package names. Trying capabilities.
No provider of 'atlascpp-devel' found.
'libreadline6' not found in package names. Trying capabilities.
No provider of 'libreadline6' found.
```

I then installed the following (shooting for parity, but unsure if this was required):
```
pango-devel
libreadline7
```
I could not find anything in `zypper search` that was `atlas` related

R worked (slightly), but threw errors that required installing:
```
libblas3
liblapack3
```

Then an error in running `capabilities()`:
```
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/opt/R/3.6.0/lib/R/modules//R_X11.so':
  libjpeg.so.62: cannot open shared object file: No such file or directory
```

Resolved by:
```
zypper install -y libjpeg62
```

OS details:
```
> cat /etc/os-release
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"
```

**Comment by glin** [comment]
Thanks for the heads up about this a while back! We just addressed these issues in the openSUSE 15 RPMs (which these images now use): https://github.com/rstudio/r-builds/pull/27

In short, libreadline6 was switched to 7, and pango-tools was replaced with libpango. I'm not sure what happened with libjpeg62, but it's in the rpm deps, so it should be there now. And the ATLAS issue was addressed earlier by switching to OpenBLAS.

The openSUSE 15 rpm should work on SLES 15, but let us know if you find otherwise. While the docs are being worked on, here's a snippet to install R on SLES 15:

```sh
# R 3.6.1
wget https://cdn.rstudio.com/r/opensuse-15/pkgs/R-3.6.1-1-1.x86_64.rpm
zypper --no-gpg-checks install R-3.6.1-1-1.x86_64.rpm

/opt/R/3.6.1/bin/R --version
```
